// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyDYgfKFYr7n48cppsOlqEsQJfUgqBt-tmI',
      appId: '1:84836536504:web:8e9a449d8ef8b24203644d',
      messagingSenderId: '84836536504',
      projectId: 'gustav-project',
      authDomain: 'gustav-project.firebaseapp.com',
      storageBucket: 'gustav-project.appspot.com',
      measurementId: 'G-HYZEYREFY9',
      databaseURL:
          'https://gustav-project-default-rtdb.asia-southeast1.firebasedatabase.app/');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMzKDo8Ib7kVorNXFXFz7zXKQme1VO5U',
    appId: '1:84836536504:android:7e4066ae41a46b5903644d',
    messagingSenderId: '84836536504',
    projectId: 'gustav-project',
    storageBucket: 'gustav-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWf5UN3OwziSGHJuC8rwgXOsU7F_pK_io',
    appId: '1:84836536504:ios:0f50a2faf6df58be03644d',
    messagingSenderId: '84836536504',
    projectId: 'gustav-project',
    storageBucket: 'gustav-project.appspot.com',
    iosBundleId: 'com.example.resumeWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWf5UN3OwziSGHJuC8rwgXOsU7F_pK_io',
    appId: '1:84836536504:ios:003edd7c4552ab4303644d',
    messagingSenderId: '84836536504',
    projectId: 'gustav-project',
    storageBucket: 'gustav-project.appspot.com',
    iosBundleId: 'com.example.resumeWeb.RunnerTests',
  );
}
